name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 14.x, 16.x]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Check current directory and list files
      run: |
        echo "Working directory:"
        pwd
        echo "List of files:"
        ls -la

    - name: Install Dependencies (Safe Fallback)
      run: |
        npm install || (echo "Initial install failed, retrying..." && npm cache clean --force && npm install)

    - name: Run Lint
      run: npm run lint

    - name: Run Tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webpack-artifacts
        path: dist/

    env:
      CI: true
